added task 4 and 5 for module 3
js-tasks-ru/jsbasic-20231211_alexgall pull request #6
Opened 2023-12-29 08:14 UTC by Alexgalll

2023-12-29 08:15 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-29 08:57 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-12-29 09:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2023-12-29 09:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2023-12-29 11:23 UTC, koalex requested changes
Исправить замечание **4-3**

2023-12-29 11:23 UTC, koalex commented on 4-module/3-task/index.js
> +      row.setAttribute("hidden", "true");
На занятии говорил, что надо написать так: `row.hidden = true;`
А так же сказала, кто этого не сделает, то верну на доработку)

2024-01-02 13:14 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-01-03 10:10 UTC, koalex approved these changes

2024-01-03 10:11 UTC, merged